using SeleniumExtras.WaitHelpers;

namespace ArmorFeedTest.VehiclesTest;

// Generated by Selenium IDE
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using Xunit;
public class SuiteTests2 : IDisposable {
  public IWebDriver driver {get; private set;}
  public IDictionary<String, Object> vars {get; private set;}
  public IJavaScriptExecutor js {get; private set;}
  public SuiteTests2()
  {
    var chromeDriverService = ChromeDriverService.CreateDefaultService(@"/Users/carlolucas/chrome-driver");
    driver = new ChromeDriver(chromeDriverService, new ChromeOptions());
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<String, Object>();
  }
  public void Dispose()
  {
    driver.Quit();
  }
  [Fact]
  public void AddVehicle() {
    driver.Navigate().GoToUrl("http://localhost:3000/sign-in");
    driver.Manage().Window.Size = new System.Drawing.Size(2560, 1340);
    driver.FindElement(By.Id("email")).Click();
    driver.FindElement(By.Id("email")).SendKeys("carlo@gmail.com");
    driver.FindElement(By.Id("password")).Click();
    driver.FindElement(By.Id("password")).SendKeys("carlo123@");
    driver.FindElement(By.CssSelector(".p-button-label:nth-child(1)")).Click();
    var wait = new WebDriverWait(driver, TimeSpan.FromSeconds(10));
    var elementoMenu = wait.Until(ExpectedConditions.ElementExists(By.LinkText("My Vehicles")));
    elementoMenu.Click();
    driver.FindElement(By.LinkText("My Vehicles")).Click();
    driver.FindElement(By.CssSelector(".p-button-error")).Click();
    driver.FindElement(By.Id("brand")).Click();
    driver.FindElement(By.Id("brand")).SendKeys("Toyota");
    driver.FindElement(By.Id("licensePlate")).Click();
    driver.FindElement(By.Id("licensePlate")).SendKeys("S2W-456");
    driver.FindElement(By.Id("year")).Click();
    driver.FindElement(By.Id("year")).SendKeys("2021");
    driver.FindElement(By.Id("model")).Click();
    driver.FindElement(By.Id("model")).SendKeys("Charge Type");
    driver.FindElement(By.Id("maintenanceDate")).Click();
    driver.FindElement(By.CssSelector("tr:nth-child(5) > td:nth-child(2) > span")).Click();
    driver.FindElement(By.CssSelector(".p-placeholder")).Click();
    driver.FindElement(By.CssSelector(".p-dropdown-item:nth-child(2)")).Click();
    driver.FindElement(By.CssSelector(".p-dialog-footer > .p-button:nth-child(2)")).Click();
  }
}